### PR TITLE
Add locale of korean

### PR DESCRIPTION
**Pull request by HotoRas**
- add korean (`ko`) as display language

### CODE REVIEW

**Comment by HotoRas** [comment]
I'll have to notify this is still draft rn- I want to translate all strings into korean and fix some typo in english (`\'` displays directly, `$,d` renders as `$d` etc).

**Comment by matsumo0922** [comment]
Nice translate! 👍 
CI seems to be failing, which I'll fix and merge in.

**Comment by HotoRas** [comment]
The commit content is done and ready to be checked- but I don't know how it will be when compiled (I worked solely on vscode and had no chance of building and flighting) so please consider about this.

**Comment by matsumo0922** [comment]
@HotoRas 

We are creating a [new repository](https://github.com/matsumo0922/PixiView-KMP), a KMP version of this application. 
We plan to develop in that repository in the future and will archive this repository.

Therefore, we have ported your PR to the [following PR](https://github.com/matsumo0922/PixiView-KMP/pull/12). 
Once again, thanks for your contribution!

**Comment by matsumo0922** [comment]
And I have submitted the app incorporating your changes to Google Play today :)

**Pull request closed without merging**
